before:
  hooks:
    - go mod download
builds:
- main: ./cmd/strava/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- github:
    owner: phogolabs
    name: homebrew-tap
  name: strava
  description: Vendoring made easy
  homepage: https://github.com/phogolabs/strava
  test: |
   system "#{bin}/strava -v"
